
#COMPUTE_MODEL = "PREDICT_LSTM"
COMPUTE_MODEL = "NO_LSTM"
#SAVE_MODEL = "SAVE_LSTM_MODEL"
SAVE_MODEL = "NO_SAVE_LSTM_MODEL"

XGBOOST = True
#XGBOOST = False
COMPUTE_DT = True
#COMPUTE_DT = False
LIGHTGBM = True
#LIGHTGBM = False

COLAB = False
#COLAB = True

DATA_SOURCE = "READ_CSV_FROM_DATABASE"
# DATA_SOURCE = "SCRAPING"

NASDAQ_100 = True
SCRAPING_NASDAQ = False
WIKI = True

DEBUG = True
DEBUG_FOCRCE_STOCK = True

SELCTION = ["GAINERS"]
#SELCTION = ["TRENDING"]
#SELCTION = ["CAC40"]
#SELCTION = ["DJI"]
#SELCTION = ["NASDAQ"]
#SELCTION = ["ACTIVES"]
#SELCTION = ["LOOSERS"]
#SELCTION = ["DAX"]
#SELCTION = ["SP500"]
#SELCTION = ["ALL"]

SAVE_5DAY_DATA = False
#SAVE_5DAY_DATA = True
SAVE_PRE_PROCESSED_DATA = False
#SAVE_PRE_PROCESSED_DATA = True