
#COMPUTE_MODEL = "PREDICT_LSTM"
COMPUTE_MODEL = "NO_LSTM"

COLAB = False
#COLAB = True

DATA_SOURCE = "READ_CSV_FROM_DATABASE"
# DATA_SOURCE = "SCRAPING"

NASDAQ_100 = True
SCRAPING_NASDAQ = False
WIKI = True